<a href="https://colab.research.google.com/github/nabilnehme/AAI614_Nehme/blob/main/Week3/Nabil_Nehme_FluWatch_PE2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

url = "https://www.canada.ca/en/public-health/services/surveillance/respiratory-virus-detections-canada/2018-2019/respiratory-virus-detections-isolations-week-01-ending-january-5-2019.html"
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

# Locate Table 2 and process it into a DataFrame
table = soup.find_all("table")[1]
rows = []

for row in table.find_all("tr")[1:]:  # Skip header
    cols = [col.get_text(strip=True) for col in row.find_all("td")]
    rows.append(cols)

# Convert table data to DataFrame as before
columns = ["Reporting Laboratory", "Flu Tested", "A(H1N1)pdm09 Positive", "A(H3) Positive", "A(UnS) Positive", "Total Flu A Positive", "Total Flu B Positive", "RSV Tested", "RSV Positive", "PIV Tested", "PIV 1 Positive", "PIV 2 Positive", "PIV 3 Positive", "PIV 4 Positive", "Other PIV Positive", "Adeno Tested", "Adeno Positive", "hMPV Tested", "hMPV Positive", "Entero/Rhino Tested", "Entero/Rhino Positive", "Coron Tested", "Coron Positive"]

df = pd.DataFrame(rows, columns=columns)

# Fill NaN values with an empty string to avoid errors with .isdigit()
df['Flu Tested'] = df['Flu Tested'].fillna("")

# Filter out rows with text data instead of numbers
df = df[df['Flu Tested'].str.isdigit()]

df

,Reporting Laboratory,Flu Tested,A(H1N1)pdm09 Positive,A(H3) Positive,A(UnS) Positive,Total Flu A Positive,Total Flu B Positive,RSV Tested,RSV Positive,PIV Tested,...,PIV 4 Positive,Other PIV Positive,Adeno Tested,Adeno Positive,hMPV Tested,hMPV Positive,Entero/Rhino Tested,Entero/Rhino Positive,Coron Tested,Coron Positive
0,Newfoundland,1299,1,0,113,114,1,1299,91,1299,...,0,0,1299,12,1299,8,1299,200,N.A.,N.A.
1,Prince Edward Island,307,38,0,0,38,0,305,5,53,...,3,0,48,5,48,0,48,21,48,0
2,Nova Scotia,864,0,0,52,52,1,869,45,322,...,1,0,322,0,322,3,322,53,322,1
3,New Brunswick,4271,42,1,715,758,2,4274,131,1185,...,29,0,1185,84,1185,7,1185,201,1185,6
4,Atlantic,6741,81,1,880,962,4,6747,272,2859,...,33,0,2854,101,2854,18,2854,475,1555,7
5,Région Nord-Est,3551,0,0,717,717,3,2633,32,0,...,0,0,0,0,0,0,N.A.,N.A.,0,0
6,Québec-Chaudière-Appalaches,5028,0,0,1098,1098,10,5039,451,1348,...,5,0,1399,60,1150,4,N.A.,N.A.,1066,3
7,Centre-du-Québec,5435,0,0,1281,1281,34,4613,350,0,...,0,0,36,0,0,0,N.A.,N.A.,0,0
8,Montréal-Laval,16318,0,0,1458,1458,19,15945,1237,9853,...,31,0,9853,313,9636,59,N.A.,N.A.,9637,307
9,Ouest du Québec,4775,0,0,925,925,9,4250,506,0,...,0,0,0,0,0,0,N.A.,N.A.,0,0
10,Montérégie,3288,0,0,495,496,6,3275,240,0,...,0,0,0,0,0,0,N.A.,N.A.,0,0
11,Province of Québec,38395,0,0,5974,5975,81,35755,2816,11201,...,36,0,11288,373,10786,63,N.A.,N.A.,10703,310
12,Ottawa P.H.L.,360,23,8,5,36,0,356,14,244,...,0,0,244,0,230,1,15,0,0,0
13,CHEO - Ottawa,3078,0,0,148,148,7,3078,248,448,...,5,0,448,16,447,5,439,132,441,16
14,Kingston P.H.L.,413,16,9,0,25,0,413,11,341,...,0,0,341,0,328,0,49,0,0,0
15,UHN / Mount Sinai Hospital,4924,0,1,249,250,9,4924,201,253,...,2,0,0,0,229,2,N.A.,N.A.,N.A.,N.A.
16,P.H.O.L. - Toronto,6435,332,114,28,474,21,6294,157,5443,...,0,0,5444,27,5310,27,245,0,0,0
17,Sick Kids Hospital - Toronto,1118,45,3,14,62,1,1062,138,1062,...,19,0,1062,30,1062,20,1062,309,1062,65
18,Sunnybrook & Women's College HSC,1139,45,14,3,62,0,1139,30,1139,...,1,0,1139,0,1139,12,1139,114,1139,30
19,Sault Ste. Marie P.H.L.,131,2,1,0,3,0,128,1,128,...,0,0,128,0,125,1,3,0,0,0
20,Timmins P.H.L.,147,18,0,0,18,0,129,0,129,...,0,0,129,0,125,1,10,0,0,0
21,St. Joseph's - London,1479,3,0,66,69,0,1479,155,656,...,11,0,656,22,656,16,512,127,438,6
22,London P.H.L.,1617,134,7,15,156,3,1589,64,1252,...,0,0,1252,11,1216,6,60,0,0,0
23,Orillia P.H.L.,379,9,1,2,12,0,379,18,310,...,0,0,310,1,302,0,10,0,0,0
24,Thunder Bay P.H.L.,134,14,0,2,16,0,126,1,117,...,0,0,117,0,112,2,5,0,0,0
25,Sudbury P.H.L.,320,4,0,0,4,0,315,11,312,...,0,0,312,2,293,3,29,0,0,0
26,Hamilton P.H.L.,1578,82,20,8,110,1,1565,54,1310,...,0,0,1310,8,1282,4,49,0,0,0
27,Peterborough P.H.L.,543,25,2,6,33,0,542,20,456,...,0,0,456,0,451,1,7,0,0,0
28,Province of Ontario,23795,752,180,546,1478,42,23518,1123,13600,...,38,0,13348,117,13307,101,3652,683,3080,117
29,Manitoba,4911,192,3,486,681,3,4828,101,2254,...,10,0,2254,25,1214,9,2254,310,1248,12
30,Regina,5329,1280,60,124,1464,1,5329,68,7262,...,32,0,5329,80,5329,35,5329,1110,5329,26
31,Saskatoon,3062,0,0,625,625,2,3062,92,3062,...,8,0,3062,26,3062,12,3062,227,3062,4
32,Province of Saskatchewan,8391,1280,60,749,2089,3,8391,160,10324,...,40,0,8391,106,8391,47,8391,1337,8391,30
33,Province of Alberta,18824,3132,73,1540,4745,29,15040,0,15040,...,154,0,15040,184,15040,189,15040,2693,15040,321
34,Prairies,32126,4604,136,2775,7515,35,28259,261,27618,...,204,0,25685,315,24645,245,25685,4340,24679,363
35,British Columbia,8731,1010,75,755,1840,10,8731,279,4342,...,66,0,4342,56,4342,14,3442,982,3442,54
36,Yukon,143,16,1,6,23,0,122,2,N.A.,...,N.A.,N.A.,N.A.,N.A.,N.A.,N.A.,N.A.,N.A.,N.A.,N.A.
37,Northwest Territories,435,138,2,0,140,0,432,0,432,...,1,0,432,12,432,2,432,82,432,4
38,Nunavut,33,8,0,0,8,0,33,0,33,...,0,0,33,5,32,0,33,10,32,0
39,Territories,611,162,3,6,171,0,587,2,465,...,1,0,465,17,464,2,465,92,464,4
40,CANADA,110399,6609,395,10936,17941,172,103597,4753,60085,...,378,0,57982,979,56398,443,36098,6572,43923,855